3 örneğimiz var.
Bu örnekler içerisinde 4'er tane etiketlerimiz var. Target alanında 0 mevcut 1 mevcut olmayan etiketleri ifade ediyor. Bu etiketler A, B, C ve D olmak üzere listelenmiştir. Bu 3 örneği eğittiğimizde bize tahmin skoru veriliyor, bu skor 0 ile 1 arasında değer alır. 1 değerine yakın olan tahmin o örnek için geçerli olma ihtimali en yüksek etiketi 0 değeri ise en düşük ihtimali ifade ediyor.
Örneğin 2. örnek için 0.9 tahmin skoruyla B etiketi geçerli olma ihtimali en yüksektir.


![Sample Data with scores](https://github.com/kmkarakaya/ML_tutorials/blob/master/images/sample%20mutli%20label%20classification%20scores.png?raw=true)


In [34]:
#Burada yukarıdaki tablonun oluşması için arrayleri kullanıyoruz
import numpy as np
y_true = np.array([[0, 1, 1, 1],[0,0,1,0],[1,1,0,0]])
y_scores = np.array([[0.2, 0.6, 0.1, 0.8],[0.4,0.9,0.8,0.6],[0.8,0.4,0.5,0.7]])

In [35]:
#Skorları tahmine çevirmek içinse threshold kullanıyoruz 
#!!Not: Kullandığımız threshold dan daha düşük değerleri 0 daha yüksek değerleri 1 olarak kabul ediyoruz
threshold = 0.5


In [36]:
#burada threshould için dizini oluşturuyoruz 
y_pred=[]
for sample in  y_scores:
  y_pred.append([1 if i>=0.5 else 0 for i in sample ] )
y_pred = np.array(y_pred)
y_pred

array([[0, 1, 0, 1],
       [0, 1, 1, 1],
       [1, 0, 1, 1]])

![Predictions](https://github.com/kmkarakaya/ML_tutorials/blob/master/images/sample%20mutli%20label%20classification%20predictionss.png?raw=true)

In [37]:
#modelimizin başarımını ölçüyoruz bu skor 1 ile 0 arasında değişir
from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)
#modelimiz için uygun değil çünkü bizim modelimiz multi label 
#olduğu için örneklere teker teker değil dörtlü bakıyor

0.0

# [Confusion matrix (Karışım Matrisi)](https://scikit-learn.org/stable/modules/model_evaluation.html#confusion-matrix) 

Karışıklık matrisi işlevi, karışıklık matrisini hesaplayarak sınıflandırma doğruluğunu değerlendirir. 

Kolonlar tahminlerimizi, satırlar ise bize verilen gerçek değerleri gösteriyor.
Negatif tahmin edilen bir veri için sonuç da negatif ise yanlış negatif değeri döner.



![Sample Confusion Matrix](https://github.com/kmkarakaya/ML_tutorials/blob/master/images/confusion%20matrix%20sample.png?raw=true)


In [42]:
#multilabel-indicator is not supported hatası alacağız (aşağıda)
from sklearn.metrics import confusion_matrix
#confusion_matrix(y_true, y_pred)

#[Multilabel confusion matrix](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.multilabel_confusion_matrix.html?highlight=multilabel#sklearn-metrics-multilabel-confusion-matrix)


* Her sınıf veya örnek için bir karışıklık matrisi hesaplıyoruz. 
* **DİKKAT:** Hücreler, bir önceki Matrix'ten farklı anlamlara sahiptir! (tahmin ve gerçeklerin yeri değişiyor.)

![MCM](https://github.com/kmkarakaya/ML_tutorials/blob/master/images/MCM%20confusion%20matrix%20sample.png?raw=true)

In [39]:
#gerçek değerler ve tahminler
print("Actual \n", y_true)
print("\nPredicted \n",y_pred)


Actual 
 [[0 1 1 1]
 [0 0 1 0]
 [1 1 0 0]]

Predicted 
 [[0 1 0 1]
 [0 1 1 1]
 [1 0 1 1]]


![Predictions](https://github.com/kmkarakaya/ML_tutorials/blob/master/images/sample%20mutli%20label%20classification%20predictionss.png?raw=true)

In [40]:
#matris, etiketler (A B C D) için tahmin edilen değerlerin sonuçlarını getiriyor
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_true, y_pred)
#örn; a için 2 tane doğru negatif 1 tane doğru pozitif döndürüyor
#bizim için önemli olan sol üstteki ve sağ alttaki değerlerin 1 veya daha fazla olmasıdır

array([[[2, 0],
        [0, 1]],

       [[0, 1],
        [1, 1]],

       [[0, 1],
        [1, 1]],

       [[0, 2],
        [0, 1]]])